package Excepions;

class Demo{
	void display() {
		try {
			System.out.println("In a try");
			System.exit(0);
		}
		finally {
			System.out.println("In a finally");
		}
	}
}

public class Exception11 {
public static void main(String[] args) {
	Demo d = new Demo();
	d.display();
}
}
